version: "3.9"

services:
    frontend:
        build: ./frontend
        entrypoint: ["/bin/sh", "-c", "npm start"]
        ports:
            - "3000:3000"
        depends_on:
            - backend 
    backend:
        build: ./backend
        entrypoint: ["/bin/bash", "-c", "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]
        volumes:
            - ./backend/src:/app
        ports:
            - "8000:8000"